name: React Native Bundle Build

on: workflow_dispatch

jobs:
  codepush-build:
    name: Build Bundle And Codepush Update
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install && npx lerna bootstrap --scope={@race-lap/app-helper,@race-lap/app-rn}

      - name: Monorepo pre-build
        run: npx lerna run build --scope="@race-lap/app-helper"

      - name: Codepush ios
        run: cd packages/app-rn && npx appcenter codepush release-react -a racelap/racelap-ios -d Production --plist-file ios/RaceLap/Info.plist
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_TOKEN_IOS }}

      - name: Codepush android
        run: cd packages/app-rn && npx appcenter codepush release-react -a racelap/racelap-android -d Production --gradle-file android/app/build.gradle
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_TOKEN_ANDROID }}
