name: Codepush IOS starter workflow

on:
  workflow_dispatch

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Bundle & Codepush Update 
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install && npx lerna bootstrap --scope="@race-lap/app-helper" --scope="@race-lap/app-rn

      - name: Monorepo pre-build
        run: npx lerna run build --scope="@race-lap/app-helper"
        
      - name: Codepush ios
        run: lerna run code-push --scope @race-lap/app-rn -- -- --appName racelap/racelap-ios --extraArgs=--plist-file\ ios/RaceLap/Info.plist    
        env:
          APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_TOKEN_IOS }}
      
      
