name: iOS starter workflow

on:
  workflow_dispatch

jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install dependencies
        run: npm install && npx lerna bootstrap

      - name: Monorepo pre-build
        # run: npx lerna run build --scope="@race-lap/app-helper" && npx lerna run build --scope="@race-lap/app-web" && npx lerna run build:ios --scope="@race-lap/app-rn"
        run: npx lerna run build --scope="@race-lap/app-helper" && npx lerna run build --scope="@race-lap/app-web"

      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: packages/app-rn/ios/RaceLap.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: packages/app-rn/ios/RaceLap.xcworkspace
          scheme: RaceLap
        # env:
        #   RCT_NO_LAUNCH_PACKAGER: ''

      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
